package com.novaris.grundstruktur;
import android.app.*;import android.os.*;import android.webkit.*;import android.widget.*;import java.io.*;
public class MainActivity extends Activity {
 private WebView web; private final String url="https://raw.githubusercontent.com/novarisartifex/Novaris-Grundstruktur-Data/main/manifest.json";
 @Override public void onCreate(Bundle b){super.onCreate(b); LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xff070a12);
 Button check=new Button(this);check.setText("Datenupdate prüfen");check.setOnClickListener(v->checkUpdate());root.addView(check);
 web=new WebView(this);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(true);web.getSettings().setAllowContentAccess(false);web.getSettings().setAllowFileAccessFromFileURLs(false);web.getSettings().setAllowUniversalAccessFromFileURLs(false);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load();}
 private void load(){File active=new File(getFilesDir(),"compendium.html");File backup=new File(getFilesDir(),"compendium.html.bak");
 if(backup.exists()&&!active.exists())backup.renameTo(active);
 if(active.exists()){web.loadUrl("file://"+active.getAbsolutePath());return;}
 try{getAssets().open("compendium.html").close();web.loadUrl("file:///android_asset/compendium.html");}catch(Exception e){web.loadDataWithBaseURL(null,"<html><body style='background:#070a12;color:#f0d991;font-family:sans-serif;padding:2em'><h2>Novaris Grundstruktur</h2><p>Originaldatei und 24 Bilddateien müssen vor Freigabe vollständig eingebunden werden.</p></body></html>","text/html","UTF-8",null);}}
 private void checkUpdate(){new Thread(()->{try{org.json.JSONObject manifest=SafeUpdates.manifest(url);if(!"published".equals(manifest.optString("status"))||manifest.isNull("latest")){runOnUiThread(()->message("Noch kein freigegebenes Datenupdate."));return;}org.json.JSONObject latest=manifest.getJSONObject("latest");int installed=getSharedPreferences("updates",0).getInt("version",0);if(latest.getInt("data_version")<=installed){runOnUiThread(()->message("Daten sind aktuell."));return;}runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Datenupdate").setMessage("Verifiziertes Update installieren?").setNegativeButton("Abbrechen",null).setPositiveButton("Installieren",(d,w)->new Thread(()->{try{SafeUpdates.install(this,latest);runOnUiThread(()->{load();message("Datenupdate installiert.");});}catch(Exception e){runOnUiThread(()->message("Update fehlgeschlagen: "+e.getMessage()));}}).start()).show());}catch(Exception e){runOnUiThread(()->message("Prüfung fehlgeschlagen: "+e.getMessage()));}}).start();}
 private void message(String text){new AlertDialog.Builder(this).setMessage(text).setPositiveButton("OK",null).show();}
}
